/* tslint:disable */
/* eslint-disable */
/**
 * total-sse-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TotalCalcPojo
 */
export interface TotalCalcPojo {
    /**
     * 
     * @type {string}
     * @memberof TotalCalcPojo
     */
    userId?: string;
    /**
     * 
     * @type {number}
     * @memberof TotalCalcPojo
     */
    totalAllowance?: number;
    /**
     * 
     * @type {number}
     * @memberof TotalCalcPojo
     */
    selfCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TotalCalcPojo
     */
    momCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TotalCalcPojo
     */
    buyCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TotalCalcPojo
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TotalCalcPojo
     */
    selfRatio?: number;
}

/**
 * Check if a given object implements the TotalCalcPojo interface.
 */
export function instanceOfTotalCalcPojo(value: object): value is TotalCalcPojo {
    return true;
}

export function TotalCalcPojoFromJSON(json: any): TotalCalcPojo {
    return TotalCalcPojoFromJSONTyped(json, false);
}

export function TotalCalcPojoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotalCalcPojo {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'totalAllowance': json['totalAllowance'] == null ? undefined : json['totalAllowance'],
        'selfCount': json['selfCount'] == null ? undefined : json['selfCount'],
        'momCount': json['momCount'] == null ? undefined : json['momCount'],
        'buyCount': json['buyCount'] == null ? undefined : json['buyCount'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'selfRatio': json['selfRatio'] == null ? undefined : json['selfRatio'],
    };
}

export function TotalCalcPojoToJSON(json: any): TotalCalcPojo {
    return TotalCalcPojoToJSONTyped(json, false);
}

export function TotalCalcPojoToJSONTyped(value?: TotalCalcPojo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'totalAllowance': value['totalAllowance'],
        'selfCount': value['selfCount'],
        'momCount': value['momCount'],
        'buyCount': value['buyCount'],
        'totalCount': value['totalCount'],
        'selfRatio': value['selfRatio'],
    };
}

