quarkus.http.port=8083
quarkus.http.host=0.0.0.0

quarkus.http.cors.enabled=true 
quarkus.http.cors.origins=http://localhost:3000

quarkus.log.category."com.marcha".level=DEBUG

quarkus.kafka.devservices.enabled=false