/* tslint:disable */
/* eslint-disable */
/**
 * obento-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BentoRecord,
} from '../models/index';
import {
    BentoRecordFromJSON,
    BentoRecordToJSON,
} from '../models/index';

export interface RecordsDateDeleteRequest {
    date: string;
    userId?: string;
}

export interface RecordsDatePutRequest {
    date: string;
    bentoRecord: BentoRecord;
}

export interface RecordsPostRequest {
    bentoRecord: BentoRecord;
}

export interface RecordsUserIdDateGetRequest {
    date: string;
    userId: string;
}

export interface RecordsUserIdGetRequest {
    userId: string;
}

/**
 * 
 */
export class BentoResourceApi extends runtime.BaseAPI {

    /**
     * Delete
     */
    async recordsDateDeleteRaw(requestParameters: RecordsDateDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling recordsDateDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/records/{date}`.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete
     */
    async recordsDateDelete(requestParameters: RecordsDateDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.recordsDateDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Update
     */
    async recordsDatePutRaw(requestParameters: RecordsDatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BentoRecord>> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling recordsDatePut().'
            );
        }

        if (requestParameters['bentoRecord'] == null) {
            throw new runtime.RequiredError(
                'bentoRecord',
                'Required parameter "bentoRecord" was null or undefined when calling recordsDatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/records/{date}`.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BentoRecordToJSON(requestParameters['bentoRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BentoRecordFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async recordsDatePut(requestParameters: RecordsDatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BentoRecord> {
        const response = await this.recordsDatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create
     */
    async recordsPostRaw(requestParameters: RecordsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BentoRecord>> {
        if (requestParameters['bentoRecord'] == null) {
            throw new runtime.RequiredError(
                'bentoRecord',
                'Required parameter "bentoRecord" was null or undefined when calling recordsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/records`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BentoRecordToJSON(requestParameters['bentoRecord']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BentoRecordFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async recordsPost(requestParameters: RecordsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BentoRecord> {
        const response = await this.recordsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Record By User Id Date
     */
    async recordsUserIdDateGetRaw(requestParameters: RecordsUserIdDateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BentoRecord>> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling recordsUserIdDateGet().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling recordsUserIdDateGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/records/{userId}/{date}`.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date']))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BentoRecordFromJSON(jsonValue));
    }

    /**
     * Get Record By User Id Date
     */
    async recordsUserIdDateGet(requestParameters: RecordsUserIdDateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BentoRecord> {
        const response = await this.recordsUserIdDateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Record By User Id
     */
    async recordsUserIdGetRaw(requestParameters: RecordsUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BentoRecord>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling recordsUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/records/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BentoRecordFromJSON));
    }

    /**
     * Get Record By User Id
     */
    async recordsUserIdGet(requestParameters: RecordsUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BentoRecord>> {
        const response = await this.recordsUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
