/* tslint:disable */
/* eslint-disable */
/**
 * total-sse-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TotalCalcPojo,
} from '../models/index';
import {
    TotalCalcPojoFromJSON,
    TotalCalcPojoToJSON,
} from '../models/index';

export interface TotalUserIdGetRequest {
    userId: string;
}

/**
 * 
 */
export class TotalResourceApi extends runtime.BaseAPI {

    /**
     * Stream
     */
    async totalUserIdGetRaw(requestParameters: TotalUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TotalCalcPojo>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling totalUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/total/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TotalCalcPojoFromJSON));
    }

    /**
     * Stream
     */
    async totalUserIdGet(requestParameters: TotalUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TotalCalcPojo>> {
        const response = await this.totalUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
